name: Nightly WDIO Run

on:
  schedule:
    - cron: '0 20 * * *'   # 2 AM Bangladesh (UTC+6)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run WebdriverIO tests
        run: npm run test
